"""
Create a program that will play the “cows and bulls” game with the user. The
game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they
have a “cow”. For every digit the user guessed correctly in the wrong place
is a “bull.” Every time the user makes a guess, tell them how many “cows” and
“bulls” they have. Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell
the user at the end.

Say the number generated by the computer is 1038. An example interaction could
look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
import random


def count_cows_and_bulks(guess_number, number):
    """Return how many cows and bulks you did in guess number."""
    cows, bulks = 0, 0

    number_map = {
        c: [idx for idx, el in enumerate(number) if el == c]
        for c in number
    }
    cow_indexes = []
    for idx, guess_el in enumerate(guess_number):
        if guess_el not in number:
            continue

        if idx in number_map[guess_el] and number[idx] == guess_el:
            cows += 1
            cow_indexes.append(idx)
            number_map[guess_el].remove(idx)

        if idx not in cow_indexes:
            bulks += 1

    return cows, bulks


rand_four_dig_number = str(random.randint(1000, 9999))
while True:
    guess_number = str(int(input('Provide 4 digits integer number: ')))
    if len(guess_number) != 4:
        print("Provide 4 digits integer number again.")

    cows, bulks = count_cows_and_bulks(guess_number, rand_four_dig_number)

    if cows == 4:
        print('Congratulations! You guessed it!')
        break

    print(f'Cows: {cows} | Bulks: {bulks}')
